// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendSQL(arg1) {
  return window['go']['controllers']['Controller']['SendSQL'](arg1);
}

export function WaveInSQL() {
  return window['go']['controllers']['Controller']['WaveInSQL']();
}
