// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetReceiveChannel():Promise<any>;

export function Listen():Promise<void>;

export function PullData(arg1:string):Promise<types.NVC_Event>;
