// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReceiveChannel():Promise<any>;

export function Listen():Promise<void>;

export function PullData(arg1:string):Promise<Array<string>>;
