// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReceiveChannel() {
  return window['go']['services']['UIReceiver']['GetReceiveChannel']();
}

export function Listen() {
  return window['go']['services']['UIReceiver']['Listen']();
}

export function PullData(arg1) {
  return window['go']['services']['UIReceiver']['PullData'](arg1);
}
