// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: nvc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SQLToChromaListenerClient is the client API for SQLToChromaListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SQLToChromaListenerClient interface {
	LogSQLAction(ctx context.Context, in *SQLAction, opts ...grpc.CallOption) (*ChromaResult, error)
}

type sQLToChromaListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewSQLToChromaListenerClient(cc grpc.ClientConnInterface) SQLToChromaListenerClient {
	return &sQLToChromaListenerClient{cc}
}

func (c *sQLToChromaListenerClient) LogSQLAction(ctx context.Context, in *SQLAction, opts ...grpc.CallOption) (*ChromaResult, error) {
	out := new(ChromaResult)
	err := c.cc.Invoke(ctx, "/nvc.SQLToChromaListener/LogSQLAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SQLToChromaListenerServer is the server API for SQLToChromaListener service.
// All implementations must embed UnimplementedSQLToChromaListenerServer
// for forward compatibility
type SQLToChromaListenerServer interface {
	LogSQLAction(context.Context, *SQLAction) (*ChromaResult, error)
	mustEmbedUnimplementedSQLToChromaListenerServer()
}

// UnimplementedSQLToChromaListenerServer must be embedded to have forward compatible implementations.
type UnimplementedSQLToChromaListenerServer struct {
}

func (UnimplementedSQLToChromaListenerServer) LogSQLAction(context.Context, *SQLAction) (*ChromaResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogSQLAction not implemented")
}
func (UnimplementedSQLToChromaListenerServer) mustEmbedUnimplementedSQLToChromaListenerServer() {}

// UnsafeSQLToChromaListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SQLToChromaListenerServer will
// result in compilation errors.
type UnsafeSQLToChromaListenerServer interface {
	mustEmbedUnimplementedSQLToChromaListenerServer()
}

func RegisterSQLToChromaListenerServer(s grpc.ServiceRegistrar, srv SQLToChromaListenerServer) {
	s.RegisterService(&SQLToChromaListener_ServiceDesc, srv)
}

func _SQLToChromaListener_LogSQLAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SQLAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SQLToChromaListenerServer).LogSQLAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvc.SQLToChromaListener/LogSQLAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SQLToChromaListenerServer).LogSQLAction(ctx, req.(*SQLAction))
	}
	return interceptor(ctx, in, info, handler)
}

// SQLToChromaListener_ServiceDesc is the grpc.ServiceDesc for SQLToChromaListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SQLToChromaListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvc.SQLToChromaListener",
	HandlerType: (*SQLToChromaListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogSQLAction",
			Handler:    _SQLToChromaListener_LogSQLAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvc.proto",
}
